//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterServiceLibrary.NodeService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NodeService1.INodeService1")]
    public interface INodeService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService1/Add", ReplyAction="http://tempuri.org/INodeService1/AddResponse")]
        double Add(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService1/Add", ReplyAction="http://tempuri.org/INodeService1/AddResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService1/Substract", ReplyAction="http://tempuri.org/INodeService1/SubstractResponse")]
        double Substract(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService1/Substract", ReplyAction="http://tempuri.org/INodeService1/SubstractResponse")]
        System.Threading.Tasks.Task<double> SubstractAsync(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INodeService1Channel : MasterServiceLibrary.NodeService1.INodeService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NodeService1Client : System.ServiceModel.ClientBase<MasterServiceLibrary.NodeService1.INodeService1>, MasterServiceLibrary.NodeService1.INodeService1 {
        
        public NodeService1Client() {
        }
        
        public NodeService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NodeService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NodeService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NodeService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double x, double y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double x, double y) {
            return base.Channel.AddAsync(x, y);
        }
        
        public double Substract(double x, double y) {
            return base.Channel.Substract(x, y);
        }
        
        public System.Threading.Tasks.Task<double> SubstractAsync(double x, double y) {
            return base.Channel.SubstractAsync(x, y);
        }
    }
}
