//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterServiceLibrary.NodeService3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NodeService3.INodeService3")]
    public interface INodeService3 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService3/Modulo", ReplyAction="http://tempuri.org/INodeService3/ModuloResponse")]
        double Modulo(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService3/Modulo", ReplyAction="http://tempuri.org/INodeService3/ModuloResponse")]
        System.Threading.Tasks.Task<double> ModuloAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService3/Pow", ReplyAction="http://tempuri.org/INodeService3/PowResponse")]
        double Pow(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INodeService3/Pow", ReplyAction="http://tempuri.org/INodeService3/PowResponse")]
        System.Threading.Tasks.Task<double> PowAsync(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INodeService3Channel : MasterServiceLibrary.NodeService3.INodeService3, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NodeService3Client : System.ServiceModel.ClientBase<MasterServiceLibrary.NodeService3.INodeService3>, MasterServiceLibrary.NodeService3.INodeService3 {
        
        public NodeService3Client() {
        }
        
        public NodeService3Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NodeService3Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NodeService3Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NodeService3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Modulo(double x, double y) {
            return base.Channel.Modulo(x, y);
        }
        
        public System.Threading.Tasks.Task<double> ModuloAsync(double x, double y) {
            return base.Channel.ModuloAsync(x, y);
        }
        
        public double Pow(double x, double y) {
            return base.Channel.Pow(x, y);
        }
        
        public System.Threading.Tasks.Task<double> PowAsync(double x, double y) {
            return base.Channel.PowAsync(x, y);
        }
    }
}
